# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'last5.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SignalViewer(object):
    def setupUi(self, SignalViewer):
        SignalViewer.setObjectName("SignalViewer")
        SignalViewer.resize(1003, 876)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/3rd biomedical/second term/DSP/task 1/visualstudio/img/signallogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SignalViewer.setWindowIcon(icon)
        SignalViewer.setIconSize(QtCore.QSize(500, 100))
        self.centralwidget = QtWidgets.QWidget(SignalViewer)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.win1 = PlotWidget(self.centralwidget)
        self.win1.setEnabled(True)
        self.win1.setMouseTracking(True)
        self.win1.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.win1.setObjectName("win1")
        self.verticalLayout.addWidget(self.win1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.startbutton1 = QtWidgets.QPushButton(self.centralwidget)
        self.startbutton1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/startgreen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startbutton1.setIcon(icon1)
        self.startbutton1.setIconSize(QtCore.QSize(30, 30))
        self.startbutton1.setObjectName("startbutton1")
        self.gridLayout_2.addWidget(self.startbutton1, 0, 0, 1, 1)
        self.pausebutton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pausebutton1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/pausegreen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pausebutton1.setIcon(icon2)
        self.pausebutton1.setIconSize(QtCore.QSize(30, 30))
        self.pausebutton1.setObjectName("pausebutton1")
        self.gridLayout_2.addWidget(self.pausebutton1, 0, 1, 1, 1)
        self.restartbutton1 = QtWidgets.QPushButton(self.centralwidget)
        self.restartbutton1.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/startg1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restartbutton1.setIcon(icon3)
        self.restartbutton1.setIconSize(QtCore.QSize(30, 30))
        self.restartbutton1.setObjectName("restartbutton1")
        self.gridLayout_2.addWidget(self.restartbutton1, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.win2 = PlotWidget(self.centralwidget)
        self.win2.setMouseTracking(True)
        self.win2.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.win2.setObjectName("win2")
        self.verticalLayout.addWidget(self.win2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.startbutton2 = QtWidgets.QPushButton(self.centralwidget)
        self.startbutton2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("img/startblue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startbutton2.setIcon(icon4)
        self.startbutton2.setIconSize(QtCore.QSize(30, 30))
        self.startbutton2.setObjectName("startbutton2")
        self.gridLayout.addWidget(self.startbutton2, 0, 0, 1, 1)
        self.win3 = PlotWidget(self.centralwidget)
        self.win3.setMouseTracking(True)
        self.win3.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.win3.setObjectName("win3")
        self.gridLayout.addWidget(self.win3, 1, 0, 1, 3)
        self.restartbutton2 = QtWidgets.QPushButton(self.centralwidget)
        self.restartbutton2.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("img/restartblue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restartbutton2.setIcon(icon5)
        self.restartbutton2.setIconSize(QtCore.QSize(30, 30))
        self.restartbutton2.setObjectName("restartbutton2")
        self.gridLayout.addWidget(self.restartbutton2, 0, 2, 1, 1)
        self.pausebutton2 = QtWidgets.QPushButton(self.centralwidget)
        self.pausebutton2.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("img/pauseblue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pausebutton2.setIcon(icon6)
        self.pausebutton2.setIconSize(QtCore.QSize(30, 30))
        self.pausebutton2.setObjectName("pausebutton2")
        self.gridLayout.addWidget(self.pausebutton2, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pausebutton3 = QtWidgets.QPushButton(self.centralwidget)
        self.pausebutton3.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("img/pausered.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pausebutton3.setIcon(icon7)
        self.pausebutton3.setIconSize(QtCore.QSize(30, 32))
        self.pausebutton3.setObjectName("pausebutton3")
        self.gridLayout_3.addWidget(self.pausebutton3, 0, 1, 1, 1)
        self.restartbutton3 = QtWidgets.QPushButton(self.centralwidget)
        self.restartbutton3.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("img/startr.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restartbutton3.setIcon(icon8)
        self.restartbutton3.setIconSize(QtCore.QSize(30, 30))
        self.restartbutton3.setObjectName("restartbutton3")
        self.gridLayout_3.addWidget(self.restartbutton3, 0, 2, 1, 1)
        self.startbutton3 = QtWidgets.QPushButton(self.centralwidget)
        self.startbutton3.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("img/resumered.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startbutton3.setIcon(icon9)
        self.startbutton3.setIconSize(QtCore.QSize(30, 30))
        self.startbutton3.setObjectName("startbutton3")
        self.gridLayout_3.addWidget(self.startbutton3, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.label1.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.verticalLayout_3.addWidget(self.label1)
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.verticalLayout_3.addWidget(self.label2)
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label3.setFont(font)
        self.label3.setObjectName("label3")
        self.verticalLayout_3.addWidget(self.label3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        SignalViewer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SignalViewer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1003, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOpenFile = QtWidgets.QMenu(self.menuFile)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("img/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuOpenFile.setIcon(icon10)
        self.menuOpenFile.setObjectName("menuOpenFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        SignalViewer.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(SignalViewer)
        self.toolBar.setIconSize(QtCore.QSize(40, 40))
        self.toolBar.setObjectName("toolBar")
        SignalViewer.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtWidgets.QStatusBar(SignalViewer)
        self.statusBar.setObjectName("statusBar")
        SignalViewer.setStatusBar(self.statusBar)
        self.actionZoomIn = QtWidgets.QAction(SignalViewer)
        self.actionZoomIn.setCheckable(False)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("img/zoominblue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomIn.setIcon(icon11)
        self.actionZoomIn.setObjectName("actionZoomIn")
        self.actionZoomOut = QtWidgets.QAction(SignalViewer)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("img/zoomoutblue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoomOut.setIcon(icon12)
        self.actionZoomOut.setObjectName("actionZoomOut")
        self.actionScroll = QtWidgets.QAction(SignalViewer)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("img/scrolllblue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionScroll.setIcon(icon13)
        self.actionScroll.setObjectName("actionScroll")
        self.actionPan = QtWidgets.QAction(SignalViewer)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("img/panblue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPan.setIcon(icon14)
        self.actionPan.setObjectName("actionPan")
        self.actionOpenCSVFile = QtWidgets.QAction(SignalViewer)
        self.actionOpenCSVFile.setIcon(icon10)
        self.actionOpenCSVFile.setObjectName("actionOpenCSVFile")
        self.actionOpentxtFile = QtWidgets.QAction(SignalViewer)
        self.actionOpentxtFile.setIcon(icon10)
        self.actionOpentxtFile.setObjectName("actionOpentxtFile")
        self.actionOpenWaveFile = QtWidgets.QAction(SignalViewer)
        self.actionOpenWaveFile.setIcon(icon10)
        self.actionOpenWaveFile.setObjectName("actionOpenWaveFile")
        self.actionSave = QtWidgets.QAction(SignalViewer)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("img/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon15)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(SignalViewer)
        self.actionExit.setObjectName("actionExit")
        self.menuOpenFile.addAction(self.actionOpenCSVFile)
        self.menuOpenFile.addAction(self.actionOpentxtFile)
        self.menuOpenFile.addAction(self.actionOpenWaveFile)
        self.menuFile.addAction(self.menuOpenFile.menuAction())
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuView.addAction(self.actionZoomIn)
        self.menuView.addAction(self.actionZoomOut)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionPan)
        self.menuView.addAction(self.actionScroll)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.toolBar.addAction(self.actionOpenCSVFile)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionZoomIn)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionZoomOut)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPan)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionScroll)

        self.retranslateUi(SignalViewer)
        QtCore.QMetaObject.connectSlotsByName(SignalViewer)

    def retranslateUi(self, SignalViewer):
        _translate = QtCore.QCoreApplication.translate
        SignalViewer.setWindowTitle(_translate("SignalViewer", "Signal Viewer"))
        self.startbutton1.setToolTip(_translate("SignalViewer", "Pause"))
        self.pausebutton1.setToolTip(_translate("SignalViewer", "Resume"))
        self.restartbutton1.setToolTip(_translate("SignalViewer", "Stop"))
        self.startbutton2.setToolTip(_translate("SignalViewer", "Pause"))
        self.restartbutton2.setToolTip(_translate("SignalViewer", "Stop"))
        self.pausebutton2.setToolTip(_translate("SignalViewer", "Resume"))
        self.pausebutton3.setToolTip(_translate("SignalViewer", "Pause"))
        self.restartbutton3.setToolTip(_translate("SignalViewer", "Resume"))
        self.startbutton3.setToolTip(_translate("SignalViewer", "Stop"))
        self.label1.setText(_translate("SignalViewer", " Channel One                             -------------------------------------------------------------------------------------------"))
        self.label2.setText(_translate("SignalViewer", " Channel Two                             -------------------------------------------------------------------------------------------"))
        self.label3.setText(_translate("SignalViewer", " Channel Three                           -------------------------------------------------------------------------------------------"))
        self.menuFile.setTitle(_translate("SignalViewer", "File"))
        self.menuOpenFile.setTitle(_translate("SignalViewer", "Open File"))
        self.menuView.setTitle(_translate("SignalViewer", "View"))
        self.toolBar.setWindowTitle(_translate("SignalViewer", "toolBar"))
        self.actionZoomIn.setText(_translate("SignalViewer", "Zoom In"))
        self.actionZoomOut.setText(_translate("SignalViewer", "Zoom Out"))
        self.actionScroll.setText(_translate("SignalViewer", "Scroll"))
        self.actionPan.setText(_translate("SignalViewer", "Pan"))
        self.actionOpenCSVFile.setText(_translate("SignalViewer", "csv File"))
        self.actionOpenCSVFile.setShortcut(_translate("SignalViewer", "Ctrl+O"))
        self.actionOpentxtFile.setText(_translate("SignalViewer", "txt File"))
        self.actionOpenWaveFile.setText(_translate("SignalViewer", "wav File"))
        self.actionSave.setText(_translate("SignalViewer", "Save"))
        self.actionSave.setShortcut(_translate("SignalViewer", "Ctrl+S"))
        self.actionExit.setText(_translate("SignalViewer", "Exit"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SignalViewer = QtWidgets.QMainWindow()
    ui = Ui_SignalViewer()
    ui.setupUi(SignalViewer)
    SignalViewer.show()
    sys.exit(app.exec_())
